namespace: scholarship-dev

environment: dev

frontend:
  image: ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/scholarship-frontend
  tag: "latest"
  replicas: 2

backend:
  image: ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/scholarship-backend
  tag: "latest"
  replicas: 2

secretNameInAWS: dev/scholarship/rds

serviceAccount:
  name: scholarship-backend-sa
  roleArn: arn:aws:iam::ACCOUNT_ID:role/scholarship-dev-secret-role

ingress:
  host: dev-scholarship.example.com