apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: rds-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.secretNameInAWS }}
        property: DB_HOST
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.secretNameInAWS }}
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.secretNameInAWS }}
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secretNameInAWS }}
        property: DB_PASSWORD